{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d06367a2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "your bet 200\n",
      "Player's Hand [1, 1, 8, 11]\n",
      "the dealer's hand is hidden\n",
      "PLAYER WINS :BLACKJACK You Win 400 €\n"
     ]
    }
   ],
   "source": [
    "card_deck=[10, 7,11, 3, 9, 9, 2,10, 4, 5, 6, 4, 11,10, 5, 8, 2, 10, 1, 9, 8, 8, 3, 11,10,3, 2, 4, 5, 10, 4,11, 10, 5, 10, 1, 3, 10, 6, 7, 10, 9, 7, 1, 6, 8, 6, 10, 1, 2, 10, 7]\n",
    "import random\n",
    "import re\n",
    "bet= int(input(\"your bet \",  ))\n",
    "while bet not in range(100,5000):\n",
    "    a=answer\n",
    "    answer=int(input(\"this table start from 100€ to 1000€\"))\n",
    "cardplayer = [1,1]\n",
    "for i in range(2):\n",
    "    random.shuffle(card_deck)\n",
    "    card= card_deck.pop()\n",
    "    cardplayer.append(card)\n",
    "print(\"Player's Hand\",cardplayer)\n",
    "carddealer = []\n",
    "for i in range(2):\n",
    "    random.shuffle(card_deck)\n",
    "    card= card_deck.pop()\n",
    "    carddealer.append(card)\n",
    "print(\"the dealer's hand is hidden\")\n",
    "if sum(cardplayer)== 21:\n",
    "    print(\"PLAYER WINS :BLACKJACK\", \"You Win\", bet*2 ,\"€\")\n",
    "while sum(cardplayer)<21:\n",
    "    answer=input(\"PLAYER do you want to draw a card yes or no?\")\n",
    "    while answer not in [\"yes\",\"YES\",\"no\",\"NO\"]:\n",
    "        a=answer\n",
    "        answer= input(\"please stop drinking & choose just yes or no\" )\n",
    "    if answer == \"yes\"or\"YES\":\n",
    "            for i in range(1):\n",
    "                random.shuffle(card_deck)\n",
    "                card= card_deck.pop()\n",
    "                cardplayer.append(card)\n",
    "            print(cardplayer if sum(cardplayer)<=21 else (cardplayer,\"PLAYER LOST, hand is over 21, Better luck next time\")) \n",
    "    if answer == \"no\"or\"NO\":\n",
    "        print(\"Hand dealer\",carddealer,  \"Hand player\",cardplayer)\n",
    "        if sum(cardplayer)<sum(carddealer):\n",
    "              print(\"PLAYER LOST, dealer's hand higher\")\n",
    "        elif sum(cardplayer)>sum(carddealer)<17:\n",
    "            while sum(carddealer)<17:\n",
    "                for i in range(1):\n",
    "                    random.shuffle(card_deck)\n",
    "                    card= card_deck.pop()\n",
    "                    carddealer.append(card)\n",
    "                if 16>sum(carddealer):\n",
    "                    print(\"Hand dealer\",carddealer)\n",
    "                    continue\n",
    "                elif 21<sum(carddealer):\n",
    "                    print(\"Hand dealer\",carddealer,\"PLAYER WINS: \", bet*2,\"€\")          \n",
    "                    break\n",
    "                elif sum(carddealer)>sum(cardplayer) :\n",
    "                    print(\"Hand dealer\",carddealer,\"PLAYER LOST, dealer's hand higher \")\n",
    "                    break\n",
    "                else:\n",
    "                    print(\"Hand dealer\",carddealer,\"PLAYER WINS: \" , bet*2,\"€\")\n",
    "            break\n",
    "        else:\n",
    "            print(carddealer,\"TIE\",cardplayer)\n",
    "        break\n",
    "                                "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "a3037dc9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "your bet50\n",
      "player's hand [2, 10]\n",
      "the dealer's hand is hidden\n",
      "PLAYER do you want to draw a card yes or no?yes\n",
      "[2, 10, 8]\n",
      "PLAYER do you want to draw a card yes or no?no\n",
      "Hand dealer [4, 3] Hand player [2, 10, 8]\n",
      "Hand dealer [4, 3, 1]\n",
      "Hand dealer [4, 3, 1, 10] PLAYER WINS:  100 €\n"
     ]
    }
   ],
   "source": [
    "card_deck=[10, 7,11, 3, 9, 9, 2,10, 4, 5, 6, 4, 11,10, 5, 8, 2, 10, 1, 9, 8, 8, 3, 11,10,3, 2, 4, 5, 10, 4,11, 10, 5, 10, 1, 3, 10, 6, 7, 10, 9, 7, 1, 6, 8, 6, 10, 1, 2, 10, 7]\n",
    "import random\n",
    "bet= int(input(\"your bet\", ))\n",
    "playercards = []\n",
    "for i in range(2):\n",
    "    random.shuffle(card_deck)\n",
    "    card= card_deck.pop()\n",
    "    playercards.append(card)\n",
    "print(\"player's hand\",playercards)\n",
    "dealercards = []\n",
    "for i in range(2):\n",
    "    random.shuffle(card_deck)\n",
    "    card= card_deck.pop()\n",
    "    dealercards.append(card)\n",
    "print(\"the dealer's hand is hidden\")\n",
    "if sum(playercards)== 21:\n",
    "    print(\"PLAYER WINS! :BLACKJACK\", \"You Win\", bet*2, \"€\")\n",
    "while sum(playercards)<21:\n",
    "    answer=input(\"PLAYER do you want to draw a card yes or no?\")\n",
    "    while answer not in [\"yes\",\"no\"]:\n",
    "        a=answer\n",
    "        answer= input(\"please stop drinking & choose yes or no\" )\n",
    "    if answer == \"yes\":\n",
    "            for i in range(1):\n",
    "                random.shuffle(card_deck)\n",
    "                card= card_deck.pop()\n",
    "                playercards.append(card)\n",
    "            print(playercards if sum(playercards)<=21 else (playercards,\"PLAYER Lost, hand is over 21, better luck next time!\", \"you lost:\", bet, \"€\")) \n",
    "    if answer == \"no\":\n",
    "        print(\"Hand dealer\",dealercards,  \"Hand player\",playercards)\n",
    "        if sum(playercards)<sum(dealercards):\n",
    "              print(\"PLAYER LOST, dealer's hand higher!\",\"you lost:\", bet, \"€\")\n",
    "        elif sum(playercards)>sum(dealercards)<17:\n",
    "            while sum(dealercards)<17:\n",
    "                    for i in range(1):\n",
    "                        random.shuffle(card_deck)\n",
    "                        card= card_deck.pop()\n",
    "                        dealercards.append(card)\n",
    "                    if 17>sum(dealercards):\n",
    "                        print(\"Hand dealer\", dealercards)\n",
    "                        continue\n",
    "                    elif 21<sum(dealercards):\n",
    "                        print(\"Hand dealer\",dealercards,\"PLAYER WINS: \", bet*2, \"€\") \n",
    "                        break\n",
    "                    elif sum(dealercards)>sum(playercards) :\n",
    "                        print(\"Hand dealer\", dealercards,\"PLAYER LOST, dealer's hand is higher! \",\"you lost:\", bet, \"€\")\n",
    "                        break\n",
    "                    \n",
    "                    else:\n",
    "                        print(\"Hand dealer\", dealercards,\"PLAYER WINS: \", bet*2,\"€\")\n",
    "            break\n",
    "        else:\n",
    "            print(dealercards,\"TIE\",playercards)\n",
    "        break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fefc770c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
